/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WashSessionRouteImport } from './routes/wash-session'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffWashSessionRouteImport } from './routes/staff.wash-session'
import { Route as StaffOperationsRouteImport } from './routes/staff.operations'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffConfirmationRouteImport } from './routes/staff.confirmation'
import { Route as StaffCheckoutRouteImport } from './routes/staff.checkout'
import { Route as StaffCheckInRouteImport } from './routes/staff.check-in'
import { Route as CustomerVehiclesRouteImport } from './routes/customer.vehicles'
import { Route as CustomerTransactionsRouteImport } from './routes/customer.transactions'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOverviewRouteImport } from './routes/customer.overview'
import { Route as CustomerLoyaltyRouteImport } from './routes/customer.loyalty'
import { Route as CustomerBookingsRouteImport } from './routes/customer.bookings'
import { Route as BookingsTrackerRouteImport } from './routes/bookings.tracker'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as AdminTiersRouteImport } from './routes/admin.tiers'
import { Route as AdminTierHistoryRouteImport } from './routes/admin.tier-history'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRbacRouteImport } from './routes/admin.rbac'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminPointsAuditRouteImport } from './routes/admin.points-audit'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as StaffCheckinIdRouteImport } from './routes/staff.checkin.$id'
import { Route as CustomerCbVehiclesRouteImport } from './routes/customer.cb.vehicles'
import { Route as CustomerCbHomeRouteImport } from './routes/customer.cb.home'
import { Route as CustomerCbHistoryRouteImport } from './routes/customer.cb.history'
import { Route as CustomerCbBookingRouteImport } from './routes/customer.cb.booking'
import { Route as CustomerBookingsTrackerRouteImport } from './routes/customer.bookings.tracker'
import { Route as CustomerBookingsNewRouteImport } from './routes/customer.bookings.new'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'

const WashSessionRoute = WashSessionRouteImport.update({
  id: '/wash-session',
  path: '/wash-session',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffWashSessionRoute = StaffWashSessionRouteImport.update({
  id: '/wash-session',
  path: '/wash-session',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOperationsRoute = StaffOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConfirmationRoute = StaffConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCheckoutRoute = StaffCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCheckInRoute = StaffCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => StaffRoute,
} as any)
const CustomerVehiclesRoute = CustomerVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerTransactionsRoute = CustomerTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOverviewRoute = CustomerOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerLoyaltyRoute = CustomerLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerRoute,
} as any)
const BookingsTrackerRoute = BookingsTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookingsRoute,
} as any)
const AdminTiersRoute = AdminTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTierHistoryRoute = AdminTierHistoryRouteImport.update({
  id: '/tier-history',
  path: '/tier-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPointsAuditRoute = AdminPointsAuditRouteImport.update({
  id: '/points-audit',
  path: '/points-audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const StaffCheckinIdRoute = StaffCheckinIdRouteImport.update({
  id: '/checkin/$id',
  path: '/checkin/$id',
  getParentRoute: () => StaffRoute,
} as any)
const CustomerCbVehiclesRoute = CustomerCbVehiclesRouteImport.update({
  id: '/cb/vehicles',
  path: '/cb/vehicles',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCbHomeRoute = CustomerCbHomeRouteImport.update({
  id: '/cb/home',
  path: '/cb/home',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCbHistoryRoute = CustomerCbHistoryRouteImport.update({
  id: '/cb/history',
  path: '/cb/history',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCbBookingRoute = CustomerCbBookingRouteImport.update({
  id: '/cb/booking',
  path: '/cb/booking',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsTrackerRoute = CustomerBookingsTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => CustomerBookingsRoute,
} as any)
const CustomerBookingsNewRoute = CustomerBookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomerBookingsRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/vehicles': typeof VehiclesRoute
  '/verify': typeof VerifyRoute
  '/wash-session': typeof WashSessionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/points-audit': typeof AdminPointsAuditRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tier-history': typeof AdminTierHistoryRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/tracker': typeof BookingsTrackerRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/loyalty': typeof CustomerLoyaltyRoute
  '/customer/overview': typeof CustomerOverviewRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/transactions': typeof CustomerTransactionsRoute
  '/customer/vehicles': typeof CustomerVehiclesRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/checkout': typeof StaffCheckoutRoute
  '/staff/confirmation': typeof StaffConfirmationRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/wash-session': typeof StaffWashSessionRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/bookings/tracker': typeof CustomerBookingsTrackerRoute
  '/customer/cb/booking': typeof CustomerCbBookingRoute
  '/customer/cb/history': typeof CustomerCbHistoryRoute
  '/customer/cb/home': typeof CustomerCbHomeRoute
  '/customer/cb/vehicles': typeof CustomerCbVehiclesRoute
  '/staff/checkin/$id': typeof StaffCheckinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/vehicles': typeof VehiclesRoute
  '/verify': typeof VerifyRoute
  '/wash-session': typeof WashSessionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/points-audit': typeof AdminPointsAuditRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tier-history': typeof AdminTierHistoryRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/tracker': typeof BookingsTrackerRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/loyalty': typeof CustomerLoyaltyRoute
  '/customer/overview': typeof CustomerOverviewRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/transactions': typeof CustomerTransactionsRoute
  '/customer/vehicles': typeof CustomerVehiclesRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/checkout': typeof StaffCheckoutRoute
  '/staff/confirmation': typeof StaffConfirmationRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/wash-session': typeof StaffWashSessionRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/bookings/tracker': typeof CustomerBookingsTrackerRoute
  '/customer/cb/booking': typeof CustomerCbBookingRoute
  '/customer/cb/history': typeof CustomerCbHistoryRoute
  '/customer/cb/home': typeof CustomerCbHomeRoute
  '/customer/cb/vehicles': typeof CustomerCbVehiclesRoute
  '/staff/checkin/$id': typeof StaffCheckinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/vehicles': typeof VehiclesRoute
  '/verify': typeof VerifyRoute
  '/wash-session': typeof WashSessionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/points-audit': typeof AdminPointsAuditRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tier-history': typeof AdminTierHistoryRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/tracker': typeof BookingsTrackerRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/loyalty': typeof CustomerLoyaltyRoute
  '/customer/overview': typeof CustomerOverviewRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/transactions': typeof CustomerTransactionsRoute
  '/customer/vehicles': typeof CustomerVehiclesRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/checkout': typeof StaffCheckoutRoute
  '/staff/confirmation': typeof StaffConfirmationRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/wash-session': typeof StaffWashSessionRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/bookings/tracker': typeof CustomerBookingsTrackerRoute
  '/customer/cb/booking': typeof CustomerCbBookingRoute
  '/customer/cb/history': typeof CustomerCbHistoryRoute
  '/customer/cb/home': typeof CustomerCbHomeRoute
  '/customer/cb/vehicles': typeof CustomerCbVehiclesRoute
  '/staff/checkin/$id': typeof StaffCheckinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/checkout'
    | '/confirmation'
    | '/customer'
    | '/login'
    | '/loyalty'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/staff'
    | '/transactions'
    | '/vehicles'
    | '/verify'
    | '/wash-session'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/points-audit'
    | '/admin/promotions'
    | '/admin/rbac'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tier-history'
    | '/admin/tiers'
    | '/bookings/new'
    | '/bookings/tracker'
    | '/customer/bookings'
    | '/customer/loyalty'
    | '/customer/overview'
    | '/customer/profile'
    | '/customer/transactions'
    | '/customer/vehicles'
    | '/staff/check-in'
    | '/staff/checkout'
    | '/staff/confirmation'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/staff/operations'
    | '/staff/wash-session'
    | '/admin/customers/$id'
    | '/customer/bookings/new'
    | '/customer/bookings/tracker'
    | '/customer/cb/booking'
    | '/customer/cb/history'
    | '/customer/cb/home'
    | '/customer/cb/vehicles'
    | '/staff/checkin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/checkout'
    | '/confirmation'
    | '/customer'
    | '/login'
    | '/loyalty'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/staff'
    | '/transactions'
    | '/vehicles'
    | '/verify'
    | '/wash-session'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/points-audit'
    | '/admin/promotions'
    | '/admin/rbac'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tier-history'
    | '/admin/tiers'
    | '/bookings/new'
    | '/bookings/tracker'
    | '/customer/bookings'
    | '/customer/loyalty'
    | '/customer/overview'
    | '/customer/profile'
    | '/customer/transactions'
    | '/customer/vehicles'
    | '/staff/check-in'
    | '/staff/checkout'
    | '/staff/confirmation'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/staff/operations'
    | '/staff/wash-session'
    | '/admin/customers/$id'
    | '/customer/bookings/new'
    | '/customer/bookings/tracker'
    | '/customer/cb/booking'
    | '/customer/cb/history'
    | '/customer/cb/home'
    | '/customer/cb/vehicles'
    | '/staff/checkin/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/checkout'
    | '/confirmation'
    | '/customer'
    | '/login'
    | '/loyalty'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/staff'
    | '/transactions'
    | '/vehicles'
    | '/verify'
    | '/wash-session'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/points-audit'
    | '/admin/promotions'
    | '/admin/rbac'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tier-history'
    | '/admin/tiers'
    | '/bookings/new'
    | '/bookings/tracker'
    | '/customer/bookings'
    | '/customer/loyalty'
    | '/customer/overview'
    | '/customer/profile'
    | '/customer/transactions'
    | '/customer/vehicles'
    | '/staff/check-in'
    | '/staff/checkout'
    | '/staff/confirmation'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/staff/operations'
    | '/staff/wash-session'
    | '/admin/customers/$id'
    | '/customer/bookings/new'
    | '/customer/bookings/tracker'
    | '/customer/cb/booking'
    | '/customer/cb/history'
    | '/customer/cb/home'
    | '/customer/cb/vehicles'
    | '/staff/checkin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  StaffRoute: typeof StaffRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
  VehiclesRoute: typeof VehiclesRoute
  VerifyRoute: typeof VerifyRoute
  WashSessionRoute: typeof WashSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wash-session': {
      id: '/wash-session'
      path: '/wash-session'
      fullPath: '/wash-session'
      preLoaderRoute: typeof WashSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/wash-session': {
      id: '/staff/wash-session'
      path: '/wash-session'
      fullPath: '/staff/wash-session'
      preLoaderRoute: typeof StaffWashSessionRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/operations': {
      id: '/staff/operations'
      path: '/operations'
      fullPath: '/staff/operations'
      preLoaderRoute: typeof StaffOperationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/confirmation': {
      id: '/staff/confirmation'
      path: '/confirmation'
      fullPath: '/staff/confirmation'
      preLoaderRoute: typeof StaffConfirmationRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/checkout': {
      id: '/staff/checkout'
      path: '/checkout'
      fullPath: '/staff/checkout'
      preLoaderRoute: typeof StaffCheckoutRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/check-in': {
      id: '/staff/check-in'
      path: '/check-in'
      fullPath: '/staff/check-in'
      preLoaderRoute: typeof StaffCheckInRouteImport
      parentRoute: typeof StaffRoute
    }
    '/customer/vehicles': {
      id: '/customer/vehicles'
      path: '/vehicles'
      fullPath: '/customer/vehicles'
      preLoaderRoute: typeof CustomerVehiclesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/transactions': {
      id: '/customer/transactions'
      path: '/transactions'
      fullPath: '/customer/transactions'
      preLoaderRoute: typeof CustomerTransactionsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/overview': {
      id: '/customer/overview'
      path: '/overview'
      fullPath: '/customer/overview'
      preLoaderRoute: typeof CustomerOverviewRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/loyalty': {
      id: '/customer/loyalty'
      path: '/loyalty'
      fullPath: '/customer/loyalty'
      preLoaderRoute: typeof CustomerLoyaltyRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/bookings/tracker': {
      id: '/bookings/tracker'
      path: '/tracker'
      fullPath: '/bookings/tracker'
      preLoaderRoute: typeof BookingsTrackerRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/admin/tiers': {
      id: '/admin/tiers'
      path: '/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AdminTiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tier-history': {
      id: '/admin/tier-history'
      path: '/tier-history'
      fullPath: '/admin/tier-history'
      preLoaderRoute: typeof AdminTierHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/points-audit': {
      id: '/admin/points-audit'
      path: '/points-audit'
      fullPath: '/admin/points-audit'
      preLoaderRoute: typeof AdminPointsAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/checkin/$id': {
      id: '/staff/checkin/$id'
      path: '/checkin/$id'
      fullPath: '/staff/checkin/$id'
      preLoaderRoute: typeof StaffCheckinIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/customer/cb/vehicles': {
      id: '/customer/cb/vehicles'
      path: '/cb/vehicles'
      fullPath: '/customer/cb/vehicles'
      preLoaderRoute: typeof CustomerCbVehiclesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cb/home': {
      id: '/customer/cb/home'
      path: '/cb/home'
      fullPath: '/customer/cb/home'
      preLoaderRoute: typeof CustomerCbHomeRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cb/history': {
      id: '/customer/cb/history'
      path: '/cb/history'
      fullPath: '/customer/cb/history'
      preLoaderRoute: typeof CustomerCbHistoryRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cb/booking': {
      id: '/customer/cb/booking'
      path: '/cb/booking'
      fullPath: '/customer/cb/booking'
      preLoaderRoute: typeof CustomerCbBookingRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings/tracker': {
      id: '/customer/bookings/tracker'
      path: '/tracker'
      fullPath: '/customer/bookings/tracker'
      preLoaderRoute: typeof CustomerBookingsTrackerRouteImport
      parentRoute: typeof CustomerBookingsRoute
    }
    '/customer/bookings/new': {
      id: '/customer/bookings/new'
      path: '/new'
      fullPath: '/customer/bookings/new'
      preLoaderRoute: typeof CustomerBookingsNewRouteImport
      parentRoute: typeof CustomerBookingsRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminPointsAuditRoute: typeof AdminPointsAuditRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTierHistoryRoute: typeof AdminTierHistoryRoute
  AdminTiersRoute: typeof AdminTiersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminPointsAuditRoute: AdminPointsAuditRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTierHistoryRoute: AdminTierHistoryRoute,
  AdminTiersRoute: AdminTiersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BookingsRouteChildren {
  BookingsNewRoute: typeof BookingsNewRoute
  BookingsTrackerRoute: typeof BookingsTrackerRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsNewRoute: BookingsNewRoute,
  BookingsTrackerRoute: BookingsTrackerRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface CustomerBookingsRouteChildren {
  CustomerBookingsNewRoute: typeof CustomerBookingsNewRoute
  CustomerBookingsTrackerRoute: typeof CustomerBookingsTrackerRoute
}

const CustomerBookingsRouteChildren: CustomerBookingsRouteChildren = {
  CustomerBookingsNewRoute: CustomerBookingsNewRoute,
  CustomerBookingsTrackerRoute: CustomerBookingsTrackerRoute,
}

const CustomerBookingsRouteWithChildren =
  CustomerBookingsRoute._addFileChildren(CustomerBookingsRouteChildren)

interface CustomerRouteChildren {
  CustomerBookingsRoute: typeof CustomerBookingsRouteWithChildren
  CustomerLoyaltyRoute: typeof CustomerLoyaltyRoute
  CustomerOverviewRoute: typeof CustomerOverviewRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerTransactionsRoute: typeof CustomerTransactionsRoute
  CustomerVehiclesRoute: typeof CustomerVehiclesRoute
  CustomerCbBookingRoute: typeof CustomerCbBookingRoute
  CustomerCbHistoryRoute: typeof CustomerCbHistoryRoute
  CustomerCbHomeRoute: typeof CustomerCbHomeRoute
  CustomerCbVehiclesRoute: typeof CustomerCbVehiclesRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerBookingsRoute: CustomerBookingsRouteWithChildren,
  CustomerLoyaltyRoute: CustomerLoyaltyRoute,
  CustomerOverviewRoute: CustomerOverviewRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerTransactionsRoute: CustomerTransactionsRoute,
  CustomerVehiclesRoute: CustomerVehiclesRoute,
  CustomerCbBookingRoute: CustomerCbBookingRoute,
  CustomerCbHistoryRoute: CustomerCbHistoryRoute,
  CustomerCbHomeRoute: CustomerCbHomeRoute,
  CustomerCbVehiclesRoute: CustomerCbVehiclesRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface StaffRouteChildren {
  StaffCheckInRoute: typeof StaffCheckInRoute
  StaffCheckoutRoute: typeof StaffCheckoutRoute
  StaffConfirmationRoute: typeof StaffConfirmationRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffOperationsRoute: typeof StaffOperationsRoute
  StaffWashSessionRoute: typeof StaffWashSessionRoute
  StaffCheckinIdRoute: typeof StaffCheckinIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCheckInRoute: StaffCheckInRoute,
  StaffCheckoutRoute: StaffCheckoutRoute,
  StaffConfirmationRoute: StaffConfirmationRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffOperationsRoute: StaffOperationsRoute,
  StaffWashSessionRoute: StaffWashSessionRoute,
  StaffCheckinIdRoute: StaffCheckinIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  StaffRoute: StaffRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
  VehiclesRoute: VehiclesRoute,
  VerifyRoute: VerifyRoute,
  WashSessionRoute: WashSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
